application: sharelink2015
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: web/static
  
- url: /index
  script: web.pages.index.app
  
- url: /Details
  script: web.pages.Details.app
  
- url: /contactUsPage
  script: web.pages.contactUsPage.app
  
- url: /contactsPage
  script: web.pages.contactsPage.app
  
- url: /MyGroups
  script: web.pages.MyGroups.app
  
- url: /MySavedLinks
  script: web.pages.MySavedLinks.app

- url: /NewLinks
  script: web.pages.NewLinks.app

- url: /Sign_up
  script: web.pages.Sign_up.app
  
- url: /
  script: web.pages.index.app
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"